site_name: Tôi luyện Tiếng Nhật - Khu học mở
site_description: Mày tránh ra để t học Tiếng Nhật.
site_author: duykhanh471  


nav:
  - 'Trang chủ':
    - 'Trang chủ': 'index.md' 
  - 'Hướng dẫn':
    - 'Học': 'guide.md'
    - 'Comprehensible Input': 'input.md'
  - 'Công cụ':
    - 'Yomitan': 'setup-yomichan.md'
    - 'Đào câu': 'sentence-mining.md'
  - 'Tài nguyên học':
    - 'Tài nguyên': 'resources.md'
  - 'Nội dung Tiếng Nhật':
    - 'Recommendation': 'recommendation.md'
      
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.expand
    - search.suggest
    - search.highlighting
    - search.share
  name: material
markdown_extensions:
  - attr_list
  
plugins:
  - privacy
  - open-in-new-tab
  
extra:
  generator: false